#!/usr/bin/env node
/**
 * Turns a products CSV into a single paste-able SQL file.
 *
 *   node scripts/csv-to-sql.mjs data/snapmart-products.csv data/snapmart-products.sql
 *
 * ## Why this exists alongside `import-csv.mjs`
 *
 * The importer is the right tool: it holds the database lock, warns about missing weights,
 * and keeps the sequence in step. This is for the other situation — somebody with a SQL
 * client open on the database and no Node toolchain to hand, who wants the catalogue in
 * without running the repository.
 *
 * The output is deliberately one `INSERT ... ON CONFLICT DO UPDATE` per row rather than one
 * giant multi-row statement: a client that fails on row 400 then tells you which row, and
 * re-running the file is safe because every row upserts.
 */

import { readFile, writeFile } from 'node:fs/promises';

/** Escape a value as a SQL string literal, or emit NULL. */
function lit(value) {
  if (value === null || value === undefined || value === '') return 'NULL';
  // Doubling the quote is the only escaping a standard-conforming string needs, and it is
  // what keeps "Haldiram's" from ending the literal three characters early.
  return `'${String(value).replaceAll("'", "''")}'`;
}

/**
 * A text literal that is never NULL.
 *
 * `lit()` maps an empty string to NULL, which is right for a nullable column and wrong
 * for `image_url`, `supplier_name` and `internal_sku` — all `NOT NULL` with no default.
 * A product with no image is a product with an empty image path, not a missing one.
 */
function text(value) {
  return `'${String(value ?? '').replaceAll("'", "''")}'`;
}

function num(value, fallback = 'NULL') {
  if (value === null || value === undefined || value === '') return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? String(n) : fallback;
}

/** Rupees to paise, as an integer. Money never travels as a float. */
function paise(value, fallback = 'NULL') {
  if (value === null || value === undefined || value === '') return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? String(Math.round(n * 100)) : fallback;
}

/** RFC 4180 enough: quoted fields, doubled quotes inside them, commas within. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;

  for (let i = 0; i < text.length; i += 1) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i += 1;
        } else quoted = false;
      } else field += ch;
      continue;
    }
    if (ch === '"') quoted = true;
    else if (ch === ',') {
      row.push(field);
      field = '';
    } else if (ch === '\n') {
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else if (ch !== '\r') field += ch;
  }
  if (field || row.length) {
    row.push(field);
    rows.push(row);
  }

  const [headers, ...body] = rows.filter((r) => r.some((c) => c.trim()));
  return body.map((cells) =>
    Object.fromEntries(headers.map((h, i) => [h.trim(), (cells[i] ?? '').trim()]))
  );
}

async function main() {
  const [csvPath, outPath, storesCsvPath] = process.argv.slice(2);
  if (!csvPath || !outPath) {
    console.error(
      'Usage: node scripts/csv-to-sql.mjs <products.csv> <out.sql> [stores.csv]'
    );
    process.exit(1);
  }

  const rows = parseCsv(await readFile(csvPath, 'utf8'));
  // Products carry a foreign key to stores, so a file that only inserts products fails
  // on an empty database with a message about a constraint rather than about the missing
  // shop. Emitting the branches first makes the file stand on its own, which is the
  // whole point of handing it to somebody with only a SQL client.
  const storeRows = storesCsvPath ? parseCsv(await readFile(storesCsvPath, 'utf8')) : [];

  const out = [
    '-- SnapMart pilot catalogue.',
    '-- Generated by scripts/csv-to-sql.mjs — do not edit by hand; regenerate instead.',
    '--',
    '-- Safe to run more than once: every row upserts on (store_id, barcode).',
    '-- Run schema.sql first; this assumes the products table and product_id_seq exist.',
    '',
    'BEGIN;',
    '',
  ];

  for (const store of storeRows) {
    // `ON CONFLICT DO NOTHING`, not DO UPDATE: a branch already in the database has been
    // configured by someone — surveyed coordinates, an authorised network, a merchant
    // VPA — and none of that is in this sheet. Overwriting it from a template would
    // silently un-configure a live shop.
    out.push(
      `INSERT INTO stores (
  id, name, address, latitude, longitude, authorized_egress_cidrs,
  advertised_ssid, merchant_vpa, merchant_display_name, is_active, is_open
) VALUES (
  ${lit(store.store_id)}, ${lit(store.name)}, ${lit(store.address)},
  ${num(store.latitude)}, ${num(store.longitude)},
  ${store.egress_cidr ? `ARRAY[${lit(store.egress_cidr)}]` : "'{}'::text[]"},
  ${text(store.ssid)}, ${lit(store.merchant_vpa)}, ${lit(store.merchant_display_name)},
  ${store.is_active === 'false' ? 'false' : 'true'}, true
)
ON CONFLICT (id) DO NOTHING;`
    );
    out.push('');
  }

  for (const row of rows) {
    const storeId = row.store_id || 'store_1';
    const price = paise(row.price_rupees, '0');
    // No cost in the supplied catalogue, and inventing one would put a fictional margin on
    // the owner's dashboard. Falls back to the sell price, which reads as zero margin.
    const cost = paise(row.cost_rupees, price);

    out.push(
      `INSERT INTO products (
  id, store_id, barcode, name, category, aisle, image_url,
  unit_price, expected_weight_grams, is_active,
  cost_price, profit_margin_pct, supplier_name, supplier_contact,
  stock_quantity, internal_sku, purchase_history,
  brand, mrp_paise, discount_paise
) VALUES (
  'prod_' || nextval('product_id_seq'), ${lit(storeId)}, ${lit(row.barcode)}, ${lit(row.name)},
  ${text(row.category || 'General')}, ${lit(row.aisle || null)}, ${text(row.image_url)},
  ${price}, ${num(row.weight_grams, '0')}, true,
  ${cost}, 0, ${text(row.supplier)}, '',
  ${num(row.stock, '0')}, ${text(row.sku)}, '[]'::jsonb,
  ${lit(row.brand)}, ${paise(row.mrp_rupees)}, ${paise(row.discount_rupees, '0')}
)
ON CONFLICT (store_id, barcode) DO UPDATE SET
  name = EXCLUDED.name, category = EXCLUDED.category, aisle = EXCLUDED.aisle,
  unit_price = EXCLUDED.unit_price, expected_weight_grams = EXCLUDED.expected_weight_grams,
  cost_price = EXCLUDED.cost_price, supplier_name = EXCLUDED.supplier_name,
  stock_quantity = EXCLUDED.stock_quantity, internal_sku = EXCLUDED.internal_sku,
  brand = EXCLUDED.brand, mrp_paise = EXCLUDED.mrp_paise,
  discount_paise = EXCLUDED.discount_paise, is_active = true;`
    );
    out.push('');
  }

  // The rows above mint ids from the sequence, but a store row inserted by hand would not.
  // Kept in step here for the same reason the importer does it: the first shop registered
  // through the console otherwise collides on an id that already exists.
  out.push(
    "SELECT setval('store_id_seq', GREATEST((SELECT COALESCE(MAX(NULLIF(regexp_replace(id, '[^0-9]', '', 'g'), '')::bigint), 0) FROM stores), 1));"
  );
  out.push('');
  out.push('COMMIT;');
  out.push('');

  await writeFile(outPath, out.join('\n'), 'utf8');
  console.log(`  ${rows.length} products -> ${outPath}`);
}

main().catch((error) => {
  console.error('\nGeneration failed:', error.message);
  process.exitCode = 1;
});
