import 'server-only';
import type { InternalProduct } from './types';

/**
 * POC catalogue. This replaces MOCK_PRODUCT_DB, which previously lived in
 * `src/lib/mockData.ts` and was imported by a client component — meaning the whole
 * product table shipped inside the browser bundle and could be read by anyone who
 * opened devtools. That is precisely what Requirement 2 rules out.
 *
 * The sensitive columns below are populated with realistic values on purpose: they give
 * the projection layer something real to withhold, so the CTO's "hidden fields are never
 * exposed" test is actually meaningful rather than passing vacuously.
 */
function product(
  partial: Omit<
    InternalProduct,
    'store_id' | 'purchase_history' | 'profit_margin_pct' | 'is_active'
  > &
    Partial<Pick<InternalProduct, 'store_id' | 'is_active'>>
): InternalProduct {
  const margin = ((partial.unit_price - partial.cost_price) / partial.unit_price) * 100;
  return {
    store_id: partial.store_id ?? 'store_1',
    is_active: partial.is_active ?? true,
    profit_margin_pct: Math.round(margin * 10) / 10,
    purchase_history: [
      { date: '2026-05-02', qty: 240, unit_cost: partial.cost_price },
      { date: '2026-06-14', qty: 180, unit_cost: Math.round(partial.cost_price * 0.97) },
    ],
    ...partial,
  };
}

export const PRODUCT_SEED: InternalProduct[] = [
  // Barcodes carried over from the original mock so existing test scans keep working.
  product({
    id: 'p1',
    barcode: '012000000133',
    name: 'Diet Pepsi 12oz Can',
    category: 'Beverages',
    image_url: '/products/diet-pepsi.png',
    unit_price: 4000,
    expected_weight_grams: 380,
    cost_price: 2600,
    supplier_name: 'PepsiCo India Distribution',
    supplier_contact: 'orders@pepsico-dist.example',
    stock_quantity: 412,
    internal_sku: 'BEV-PEP-DT-12',
  }),
  product({
    id: 'p2',
    barcode: '049000028904',
    name: 'Coca-Cola 20oz Bottle',
    category: 'Beverages',
    image_url: '/products/coca-cola.png',
    unit_price: 6000,
    expected_weight_grams: 620,
    cost_price: 3900,
    supplier_name: 'Hindustan Coca-Cola Beverages',
    supplier_contact: 'supply@hccb.example',
    stock_quantity: 288,
    internal_sku: 'BEV-COK-20',
  }),
  product({
    id: 'p3',
    barcode: '8901030865278',
    name: 'Amul Gold Full Cream Milk 1L',
    category: 'Dairy',
    image_url: '/products/amul-gold.png',
    unit_price: 7200,
    expected_weight_grams: 1030,
    cost_price: 6100,
    supplier_name: 'Amul Dairy Co-operative',
    supplier_contact: 'b2b@amul.example',
    stock_quantity: 96,
    internal_sku: 'DRY-AML-GLD-1L',
  }),
  product({
    id: 'p4',
    barcode: '8901719101106',
    name: 'Britannia Good Day Cashew 200g',
    category: 'Snacks',
    image_url: '/products/good-day.png',
    unit_price: 5000,
    expected_weight_grams: 205,
    cost_price: 3400,
    supplier_name: 'Britannia Industries',
    supplier_contact: 'trade@britannia.example',
    stock_quantity: 154,
    internal_sku: 'SNK-BRT-GD-200',
  }),
  product({
    id: 'p5',
    barcode: '8904004400015',
    name: 'Tata Salt 1kg',
    category: 'Staples',
    image_url: '/products/tata-salt.png',
    unit_price: 2800,
    expected_weight_grams: 1010,
    cost_price: 2100,
    supplier_name: 'Tata Consumer Products',
    supplier_contact: 'distribution@tataconsumer.example',
    stock_quantity: 320,
    internal_sku: 'STP-TAT-SLT-1K',
  }),
  product({
    id: 'p6',
    barcode: '8901058000108',
    name: 'Maggi 2-Minute Noodles 70g',
    category: 'Staples',
    image_url: '/products/maggi.png',
    unit_price: 1400,
    expected_weight_grams: 73,
    cost_price: 1000,
    supplier_name: 'Nestle India',
    supplier_contact: 'orders@nestle-in.example',
    stock_quantity: 640,
    internal_sku: 'STP-MAG-70',
  }),
  product({
    id: 'p7',
    barcode: '8901396160205',
    name: 'Colgate Strong Teeth 200g',
    category: 'Personal Care',
    image_url: '/products/colgate.png',
    unit_price: 11000,
    expected_weight_grams: 240,
    cost_price: 7700,
    supplier_name: 'Colgate-Palmolive India',
    supplier_contact: 'supply@colgate-in.example',
    stock_quantity: 78,
    internal_sku: 'PC-CLG-ST-200',
  }),
  product({
    id: 'p8',
    barcode: '8901030634567',
    name: 'Surf Excel Easy Wash 1kg',
    category: 'Household',
    image_url: '/products/surf-excel.png',
    unit_price: 13500,
    expected_weight_grams: 1040,
    cost_price: 9800,
    supplier_name: 'Hindustan Unilever',
    supplier_contact: 'trade@hul.example',
    stock_quantity: 45,
    internal_sku: 'HH-SRF-EW-1K',
  }),
  product({
    id: 'p9',
    barcode: '8901725110016',
    name: 'Aashirvaad Atta 5kg',
    category: 'Staples',
    image_url: '/products/aashirvaad.png',
    unit_price: 27500,
    expected_weight_grams: 5060,
    cost_price: 23000,
    supplier_name: 'ITC Foods',
    supplier_contact: 'foods@itc.example',
    stock_quantity: 62,
    internal_sku: 'STP-ASH-ATT-5K',
  }),
  product({
    id: 'p10',
    barcode: '8901491101820',
    name: 'Lay’s Classic Salted 52g',
    category: 'Snacks',
    image_url: '/products/lays.png',
    unit_price: 2000,
    expected_weight_grams: 55,
    cost_price: 1300,
    supplier_name: 'PepsiCo India Distribution',
    supplier_contact: 'orders@pepsico-dist.example',
    stock_quantity: 510,
    internal_sku: 'SNK-LAY-CS-52',
  }),
  product({
    id: 'p11',
    barcode: '8901063093027',
    name: 'Nescafe Classic Coffee 50g',
    category: 'Beverages',
    image_url: '/products/nescafe.png',
    unit_price: 19000,
    expected_weight_grams: 78,
    cost_price: 14200,
    supplier_name: 'Nestle India',
    supplier_contact: 'orders@nestle-in.example',
    stock_quantity: 88,
    internal_sku: 'BEV-NES-CL-50',
  }),
  product({
    id: 'p12',
    barcode: '8906002490011',
    name: 'Fortune Sunflower Oil 1L',
    category: 'Staples',
    image_url: '/products/fortune-oil.png',
    unit_price: 15500,
    expected_weight_grams: 920,
    cost_price: 13100,
    supplier_name: 'Adani Wilmar',
    supplier_contact: 'sales@adaniwilmar.example',
    stock_quantity: 130,
    internal_sku: 'STP-FRT-SFO-1L',
  }),

  // A second store, to prove store-scoping is enforced rather than assumed.
  product({
    id: 'p13',
    store_id: 'store_2',
    barcode: '012000000133',
    name: 'Diet Pepsi 12oz Can',
    category: 'Beverages',
    image_url: '/products/diet-pepsi.png',
    // Deliberately a different price from store_1's identical barcode: if store scoping
    // ever regresses, this mismatch surfaces it immediately.
    unit_price: 4200,
    expected_weight_grams: 380,
    cost_price: 2600,
    supplier_name: 'PepsiCo India Distribution',
    supplier_contact: 'orders@pepsico-dist.example',
    stock_quantity: 210,
    internal_sku: 'BEV-PEP-DT-12',
  }),
  product({
    id: 'p14',
    store_id: 'store_2',
    barcode: '8901058000108',
    name: 'Maggi 2-Minute Noodles 70g',
    category: 'Staples',
    image_url: '/products/maggi.png',
    unit_price: 1500,
    expected_weight_grams: 73,
    cost_price: 1000,
    supplier_name: 'Nestle India',
    supplier_contact: 'orders@nestle-in.example',
    stock_quantity: 300,
    internal_sku: 'STP-MAG-70',
  }),
];
